version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=messages
      - CLICKHOUSE_USER=clickhouse-user
      - CLICKHOUSE_PASSWORD=secret

  tn-message-collector:
    image: message_collector:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 100M
    container_name: tn-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=HPiv1pzIPRc --stream_name=TN
    restart: unless-stopped

  c5n-message-collector:
    image: message_collector:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 100M
    container_name: c5n-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=39RJ2lb2irE --stream_name=C5N
    restart: unless-stopped

  a24-message-collector:
    image: message_collector:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 100M
    container_name: a24-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=QGpHLgRnrx4 --stream_name=A24
    restart: unless-stopped

  jupyterlab:
    image: amalic/jupyterlab
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
    container_name: jupyterlab
    ports: 
      - "8888:8888"
    environment: 
      - PASSWORD=secret

  sentiment:
    build:
      context: ./src/models/sentiment
    container_name: sentiment
    restart: unless-stopped

  embedding:
    build:
      context: ./src/models/embedding
    container_name: embedding
    restart: unless-stopped
    ports:
      - "5000:5000"
