version: '3'
# TODO volumes
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=messages
      - CLICKHOUSE_USER=clickhouse-user
      - CLICKHOUSE_PASSWORD=secret

  tn-message-collector:
    build:
      context: ./src/message_collector
    container_name: tn-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=HPiv1pzIPRc --stream_name=TN
    restart: always

  c5n-message-collector:
    build:
      context: ./src/message_collector
    container_name: c5n-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=39RJ2lb2irE --stream_name=C5N
    restart: always

  a24-message-collector:
    build:
      context: ./src/message_collector
    container_name: a24-message-collector
    depends_on:
      - clickhouse
    command: python __main__.py --clickhouse_host=clickhouse --clickhouse_port=8123 --clickhouse_username=clickhouse-user --clickhouse_password=secret --video-id=QGpHLgRnrx4 --stream_name=A24
    restart: always

  jupyterlab:
    image: amalic/jupyterlab
    container_name: jupyterlab
    ports: 
      - "8888:8888"
    environment: 
      - PASSWORD=secret
